import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Importance Leadership</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex min-h-screen flex-col items-center justify-center">
          <h1 className="text-4xl font-bold">
            Welcome to Importance Leadership
          </h1>
          <p className="mt-4 text-lg">
            Our Next.js site is under construction.
          </p>
        </div>
      </main>
    </>
  );
}
